# Generated by Django 3.2.6 on 2021-08-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_deck_flashcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='author',
        ),
    ]
